apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: webserver
  name: webserver
spec:
  containers:
  - image: avwsolutions/falco-demo:1
    name: webserver
    ports:
    - containerPort: 3333
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
